version: '3'

services:

  db:
    user: "${USER_ID}:${GROUP_ID}"
    image: mariadb:10.6
    container_name: nextcloud_stack_db
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    environment:
        MARIADB_DATABASE: ${DB_DATABASE}
        MARIADB_USER: ${DB_USER}
        MARIADB_PASSWORD: ${DB_PASSWORD}
        MARIADB_ROOT_HOST: ${DB_ROOT_HOST}
        MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MARIADB_AUTO_UPGRADE: ${DB_AUTO_UPGRADE}
        MARIADB_DISABLE_UPGRADE_BACKUP: ${DB_DISABLE_UPGRADE_BACKUP}
    volumes:
      - db_data:/var/lib/mysql:Z
      #- ${DB_INIT_FILE}:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nextcloud_net

  redis:
    user: "${USER_ID}:${GROUP_ID}"
    image: redis:alpine
    container_name: nextcloud_stack_redis
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    volumes:
      - redis_data:/data
    networks:
      - nextcloud_net

  nextcloud:
    user: "${USER_ID}:${GROUP_ID}"
    image: nextcloud:fpm-alpine
    container_name: nextcloud_stack_nextcloud
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"
    environment:
      MYSQL_HOST: db
      REDIS_HOST: redis
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_DATA_DIR: ${NEXTCLOUD_DATA_DIR}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      PHP_UPLOAD_LIMIT: ${PHP_UPLOAD_LIMIT}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - nextcloud_app_data:/var/www/html:z
      - nextcloud_datadir:/datadir:z
      # Introduced redis session handler does not work with non-root images
      # https://github.com/nextcloud/docker/issues/763
      - ${REDIS_VOLUME_PATH}/redis-session.ini:/usr/local/etc/php/conf.d/redis-session.ini
    networks:
      - nextcloud_net
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: nextcloud_stack_nginx
    restart: unless-stopped
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ${NGINX_VOLUME_PATH}/nginx.conf:/etc/nginx/nginx.conf
      - nextcloud_app_data:/var/www/html:z,ro
    networks:
      - nextcloud_net
    depends_on:
      - nextcloud

# (!) cron job issue -> https://github.com/nextcloud/docker/issues/1695
#  cron:
#    #user: "${USER_ID}:${GROUP_ID}"
#    image: nextcloud:fpm-alpine
#    container_name: nextcloud_stack_cron
#    restart: unless-stopped
#    volumes:
#      - nextcloud_app_data:/var/www/html:z
#    entrypoint: /cron.sh
#    networks:
#      - nextcloud_net
#    depends_on:
#      - nextcloud


networks:
  nextcloud_net:
    name: nextcloud_stack_net
    driver: bridge
    attachable: true
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.driver.mtu: "1500"
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}


volumes:
  db_data:
    name: nextcloud_stack_volume_db
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DB_VOLUME_PATH}
  redis_data:
    name: nextcloud_stack_volume_redis
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${REDIS_VOLUME_PATH}
  nextcloud_app_data:
    name: nextcloud_stack_volume_nextcloud_app
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${NEXTCLOUD_APP_VOLUME_PATH}
  nextcloud_datadir:
    name: nextcloud_stack_volume_nextcloud_datadir
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${NEXTCLOUD_DATADIR_VOLUME_PATH}
